await $.import("sap.hana.xs.libs.dbutils", "xsds");
var XSDS = $.sap.hana.xs.libs.dbutils.xsds;

var body = $.request.body.asString();

var overallsoData = JSON.parse(body);

var responseBody = '';
var so_items;
var gross_amt = 0;
var prod_price = 0;
var lv_productid;
var lv_price;
var lv_quantity;
var lv_netamount;
var lv_taxamount;
var lv_grossamount;
var item_id = 10;
var lv_so_netamount = 0;
var lv_so_grossamount = 0;
var lv_so_taxamount = 0;
var i = 0;
var lv_bp_id;
var lv_company;
var lv_table;
var lv_tax = 0;
var lv_item_id;
var result;
var rs, pstmt, pc;

responseBody += 'BP_ID:' + encodeURI(overallsoData.PARTNERID) + "\n";

var conn = XSDS.Transaction.$getConnection();


pstmt = conn.prepareStatement('SELECT \"sap.hana.democontent.epm.data::salesOrderId\".NEXTVAL as OverallId from Dummy');
rs = await pstmt.executeQuery();

var overAllId = '';
if (await rs.next()) {
    overAllId = rs.getNString(1);
    responseBody += 'so id ' + overAllId + '\n';
}
await rs.close();
await pstmt.close();

lv_bp_id = encodeURI(overallsoData.PARTNERID);

var bp = XSDS.$importEntity("sap.hana.democontent.epm.data", "MD.BusinessPartner", {}, { $schemaName: "SAP_HANA_DEMO" });
var prod = XSDS.$importEntity("sap.hana.democontent.epm.data", "MD.Products" , {} , { $schemaName: "SAP_HANA_DEMO" });
var soHeader = XSDS.$importEntity("sap.hana.democontent.epm.data", "SO.Header", {}, { $schemaName: "SAP_HANA_DEMO" });
var soItem = XSDS.$importEntity("sap.hana.democontent.epm.data", "SO.Item", {}, { $schemaName: "SAP_HANA_DEMO" });
var emp = XSDS.$importEntity("sap.hana.democontent.epm.data", "MD.Employees", {}, { $schemaName: "SAP_HANA_DEMO" });
var empdetails = emp.$get({ EMPLOYEEID: '0000000033' });

var bpdetails = bp.$get({ PARTNERID: lv_bp_id });
lv_company = bpdetails.COMPANYNAME;
responseBody += 'lv_company ' + lv_company + '\n';

so_items = overallsoData.SalesOrderItems;

var newSO = new soHeader(
{   SALESORDERID:'0'+ overAllId,
    HISTORY:{CREATEDBY:empdetails,CREATEDAT:new Date() },
    NOTEID:'NOTE1234',
    PARTNER:bpdetails,
	CURRENCY:'EUR',
	LIFECYCLESTATUS:'N',
	BILLINGSTATUS:'I',
	DELIVERYSTATUS:'I' }
);
newSO.$save();
XSDS.Transaction.$commit();

var sodetails = soHeader.$get({ SALESORDERID:'0'+ overAllId });
var proddetails;
var newItem;
//Insert all Sales Order Items
if (so_items) {

    for (i; i < so_items.length; i++) {
        responseBody += 'item' + i + ' ' + 'Product_Id:' + so_items[i].Product_Id;
        responseBody += 'item' + i + ' ' + 'Quantity:' + so_items[i].Quantity;
        lv_productid = encodeURI(so_items[i].Product_Id);
        lv_quantity = encodeURI(so_items[i].Quantity);
        // Get price of the product from Product table
        proddetails = prod.$get({ PRODUCTID: lv_productid });
        lv_price = proddetails.PRICE;
        responseBody += 'lv_price ' + lv_price + '\n';
         pstmt = conn.prepareStatement("create local temporary table #TT_IN(PARTNERID nvarchar(10),COMPANYNAME nvarchar(80),PRODUCTID nvarchar(10))");
        rs = await pstmt.execute();
        await pstmt.close();

        //Insert values into the local temporary table for bp id,company name and product id for the tax calculation
        try {
            pstmt = conn.prepareStatement("insert into  #TT_IN values (?,?,?)");
            pstmt.setString(1, lv_bp_id);
            pstmt.setString(2, lv_company);
            pstmt.setString(3, lv_productid);

            rs = await pstmt.execute();
            await pstmt.close();
        } catch (e) {
            result += e.toString();
        }

        //Call the Procedure for Tax Calculation generated by the Decision Table
        pc = conn.prepareCall('CALL \"sap.hana.democontent.epm.models::DT_TAX_CALCULATION\"(#TT_IN, ?) WITH OVERVIEW');

        rs = await pc.execute();

        //Get the temporary output table name    
        rs = pc.getResultSet();
        while (await rs.next()) {
            lv_table = rs.getString(2);
        }

        //Get the Tax code value from the output table for the Company Name and Product ID
        pstmt = conn.prepareStatement('SELECT TAX from ' + lv_table);
        rs = await pstmt.executeQuery();

        if (await rs.next()) {
            lv_tax = rs.getFloat(1);
            responseBody += 'lv_tax ' + lv_tax + '\n';
        }

        lv_netamount = lv_price * lv_quantity;
        //Get the tax amount based on the tax code
        lv_taxamount = lv_netamount * lv_tax;
        lv_grossamount = lv_netamount + lv_taxamount;
        
         if (item_id >= 100) {
            lv_item_id ='0000000' + item_id;
        } else {
            lv_item_id ='00000000' + item_id;
        }
        try {
        newItem = new soItem(
		
		{   SALESORDERID:'0'+ overAllId,
			SALESORDERITEM:lv_item_id,
			PRODUCT:proddetails,
			NOTEID:'',
			CURRENCY:"EUR",
			GROSSAMOUNT:lv_grossamount,
            NETAMOUNT:lv_netamount,
            TAXAMOUNT:lv_taxamount,
            ITEMATPSTATUS:"I",
            OPITEMPOS:'',
		    QUANTITY:parseInt(lv_quantity, 10),
		    QUANTITYUNIT:"EA",
		    DELIVERYDATE:new Date()
		});
		 newItem.$save();
        } catch(e) {
            result += e.toString();
        }
 
       
        item_id = item_id + 10;

        //Calculate the total of net amount, gross amount and tax amount for all line items
        lv_so_netamount = lv_so_netamount + lv_netamount;
        lv_so_grossamount = lv_so_grossamount + lv_grossamount;
        lv_so_taxamount = lv_so_taxamount + lv_taxamount;

        //drop the local temporary table
        pstmt = conn.prepareStatement("drop table #TT_IN");
        rs = await pstmt.execute();
        await pstmt.close();
    }
}

newSO.GROSSAMOUNT = lv_so_grossamount;
newSO.NETAMOUNT = lv_so_netamount;
newSO.TAXAMOUNT= lv_so_taxamount;
newSO.$save();
XSDS.Transaction.$commit();

$.response.status = $.net.http.CREATED;
await $.response.setBody(responseBody);
export default {XSDS,body,overallsoData,responseBody,so_items,gross_amt,prod_price,lv_productid,lv_price,lv_quantity,lv_netamount,lv_taxamount,lv_grossamount,item_id,lv_so_netamount,lv_so_grossamount,lv_so_taxamount,i,lv_bp_id,lv_company,lv_table,lv_tax,lv_item_id,result,rs,pstmt,pc,conn,overAllId,bp,prod,soHeader,soItem,emp,empdetails,bpdetails,newSO,sodetails,proddetails,newItem};
