/* Create Sales Order with multiple line items*/
var body = $.request.body.asString();

var overallsoData = JSON.parse(body);

var responseBody = '';
var so_items;
var gross_amt = 0;
var prod_price = 0;
var lv_productid;
var lv_price;
var lv_quantity;
var lv_netamount;
var lv_taxamount;
var lv_grossamount;
var item_id = 10;
var lv_so_netamount = 0;
var lv_so_grossamount = 0;
var lv_so_taxamount = 0;
var i = 0;
var lv_bp_id;
var lv_company;
var lv_table;
var lv_tax = 0;
var result;
var rs, query, pc;
var taxCalculator;
var finalItemId;
responseBody += 'BP_ID:' + encodeURI(overallsoData.PARTNERID) + "\n";

var conn = await $.hdb.getConnection();

query = 'SELECT \"SAP_HANA_DEMO\".\"sap.hana.democontent.epm.data::salesOrderId\".NEXTVAL as OverallId from Dummy';


rs = await conn.executeQuery(query);
var overAllId = '';

if (rs.length > 0) {
    overAllId = rs[0].OVERALLID;
    responseBody += 'so id ' + overAllId + '\n';
}

//Get the company name for the BP id and store it in a local variable
lv_bp_id = encodeURI(overallsoData.PARTNERID);
//use prepared statement to avoid sql injection attacks
query = 'SELECT COMPANYNAME from"sap.hana.democontent.epm.data::MD.BusinessPartner" where PARTNERID = ?';
rs = await conn.executeQuery(query, lv_bp_id);

if (rs.length > 0) {
    lv_company = rs[0].COMPANYNAME;
    responseBody += 'lv_company ' + lv_company + '\n';
}

so_items = overallsoData.SalesOrderItems;


//Insert all Sales Order Items
if (so_items) {

    for (i; i < so_items.length; i++) {
        responseBody += 'item' + i + ' ' + 'Product_Id:' + so_items[i].Product_Id;
        responseBody += 'item' + i + ' ' + 'Quantity:' + so_items[i].Quantity;

        lv_productid = encodeURI(so_items[i].Product_Id);
        lv_quantity = encodeURI(so_items[i].Quantity);
        // Get price of the product from Product table
        query = 'SELECT PRICE from"sap.hana.democontent.epm.data::MD.Products" where PRODUCTID = ?';
        rs = await conn.executeQuery(query, lv_productid);

        if (rs.length > 0) {
            lv_price = rs[0].PRICE;
            responseBody += 'lv_price ' + lv_price + '\n';
        }

        //create local temporary table to pass as input to the Decision Table Procedure for Tax calculation
        query = "create local temporary table \"SAP_HANA_DEMO\".#TT_IN(PARTNERID nvarchar(10),COMPANYNAME nvarchar(80),PRODUCTID nvarchar(10))";
        await conn.executeUpdate(query);

        //Insert values into the local temporary table for bp id,company name and product id for the tax calculation
        try {
            query = "insert into \"SAP_HANA_DEMO\".#TT_IN values (?,?,?)";
            await conn.executeUpdate(query, lv_bp_id, lv_company, lv_productid);
        } catch (e) {
            result += e.toString();
        }

        //Call the Procedure for Tax Calculation generated by the Decision Table
        taxCalculator = await conn.loadProcedure('sap.hana.democontent.epm.models::DT_TAX_CALCULATION');

        rs = taxCalculator([{PARTNERID: lv_bp_id, COMPANYNAME: lv_company, PRODUCTID: lv_productid}]);

        //Get the temporary output table name    
        if (rs.length > 0) {
            // lv_table = rs[i].table;
            lv_tax = rs[0].RETURNED_TT.TAX;
            responseBody += 'lv_tax ' + lv_tax + '\n';
        }

        lv_netamount = lv_price * lv_quantity;
        //Get the tax amount based on the tax code
        lv_taxamount = lv_netamount * lv_tax;
        lv_grossamount = lv_netamount + lv_taxamount;
        //Insert Item into table
        query = 'insert into"sap.hana.democontent.epm.data::SO.Item"' + " values(?,?,?,'','EUR',?,?,?,'I','',?,'EA','')";
        finalItemId = '';
        if (item_id >= 100) {
            finalItemId = '0000000' + item_id;
        } else {
            finalItemId = '00000000' + item_id;
        }

        rs = await conn.executeUpdate(query, '0' + overAllId, finalItemId, lv_productid, lv_grossamount,
                                lv_netamount, lv_taxamount, lv_quantity);

        item_id = item_id + 10;

        //Calculate the total of net amount, gross amount and tax amount for all line items
        lv_so_netamount = lv_so_netamount + lv_netamount;
        lv_so_grossamount = lv_so_grossamount + lv_grossamount;
        lv_so_taxamount = lv_so_taxamount + lv_taxamount;

        //drop the local temporary table
        query = "drop table \"SAP_HANA_DEMO\".#TT_IN";
        rs = await conn.executeUpdate(query);

    }

}

//Insert Sales Order Header
query = 'insert into \"SAP_HANA_DEMO\".\"sap.hana.democontent.epm.data::SO.Header\"' 
        + " values(?,'0000000033',CURRENT_DATE,'0000000033',CURRENT_DATE,''," 
        + "?,'EUR',?,?,?,'N','I','I')";

rs = await conn.executeUpdate(query, '0' + overAllId, overallsoData.PARTNERID,
                        lv_so_grossamount, lv_so_netamount, lv_so_taxamount);

await conn.commit();
await conn.close();

$.response.status = $.net.http.CREATED;
await $.response.setBody(responseBody);
export default {body,overallsoData,responseBody,so_items,gross_amt,prod_price,lv_productid,lv_price,lv_quantity,lv_netamount,lv_taxamount,lv_grossamount,item_id,lv_so_netamount,lv_so_grossamount,lv_so_taxamount,i,lv_bp_id,lv_company,lv_table,lv_tax,result,rs,query,pc,taxCalculator,finalItemId,conn,overAllId};
